server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ibanking
    username: ibanking
    password: ibanking
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: iannwendii@gmail.com
    password: your-app-password-here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          allow8bitmime: true
          sendpartial: true
        debug: true

app:
  security:
    jwtSecret: "change-this-secret-key-to-a-long-random-string"
    jwtExpirationMinutes: 60
  otp:
    ttlSeconds: 120
    length: 6
    maxAttempts: 5

logging:
  level:
    root: INFO


