server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ibanking
    username: ibanking
    password: ibanking
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  security:
    jwtSecret: "change-this-secret-key-to-a-long-random-string"
    jwtExpirationMinutes: 60
  otp:
    ttlSeconds: 120
    length: 6
    maxAttempts: 5

logging:
  level:
    root: INFO


